/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import entities.Abonne;
import entities.Abonnement;
import services.AbonneService;
import services.AbonnementService;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author pc
 */
public class AbonnementFrame extends javax.swing.JInternalFrame {

    // ================== ATTRIBUTS METIER ==================
    private AbonneService abonneService;
    private AbonnementService abonnementService;

    private DefaultTableModel modelAbonne;
    private DefaultTableModel modelAbonnement;

    // Liste complète des abonnés (pour filtrer)
    private List<Abonne> allAbonnes;

    // Abonné sélectionné pour créer / modifier un abonnement
    private Abonne currentAbonne;

    /**
     * Creates new form Abonnement
     */
    public AbonnementFrame() {
        initComponents();

        abonneService = new AbonneService();
        abonnementService = new AbonnementService();

        modelAbonne = (DefaultTableModel) tableAbonne.getModel();
        modelAbonnement = (DefaultTableModel) tableabonnement.getModel();

        loadAllAbonnes();
        loadAbonnements();

        // Quand on clique une ligne dans la table Abonne
        tableAbonne.getSelectionModel().addListSelectionListener(
            new ListSelectionListener() {
                @Override
                public void valueChanged(ListSelectionEvent e) {
                    if (!e.getValueIsAdjusting()) {
                        selectAbonneFromTable();
                    }
                }
            }
        );

        // Quand on clique une ligne dans table Abonnement
        tableabonnement.getSelectionModel().addListSelectionListener(
            new ListSelectionListener() {
                @Override
                public void valueChanged(ListSelectionEvent e) {
                    if (!e.getValueIsAdjusting()) {
                        selectAbonnementFromTable();
                    }
                }
            }
        );
    }

    // ====================== CHARGEMENT DES TABLES ======================

    private void loadAllAbonnes() {
        allAbonnes = abonneService.findAll();
        modelAbonne.setRowCount(0);

        for (Abonne a : allAbonnes) {
            modelAbonne.addRow(new Object[] {
                a.getId(), a.getNom(), a.getPrenom(), a.getAge(), a.getSexe()
            });
        }
    }

    private void loadAbonnements() {
        modelAbonnement.setRowCount(0);

        for (Abonnement abo : abonnementService.findAll()) {
            Abonne a = abo.getAbonne();
            String nomComplet = (a != null) ? a.getNom() + " " + a.getPrenom() : "";

            modelAbonnement.addRow(new Object[] {
                abo.getId(),
                nomComplet,           // colonne "idabonne" mais on affiche Nom + Prénom
                abo.getType(),
                abo.getDuree(),
                abo.getPrix()
            });
        }
    }

    // ====================== SELECTION DANS TABLE ABONNE ======================

    private void selectAbonneFromTable() {
        int row = tableAbonne.getSelectedRow();
        if (row == -1) return;

        int idAbonne = (int) tableAbonne.getValueAt(row, 0);
        currentAbonne = abonneService.findById(idAbonne);

        // Ici je n'affiche pas de JOptionPane pour ne pas déranger,
        // mais tu peux le remettre si tu veux.
        // JOptionPane.showMessageDialog(this, "Abonné sélectionné : "
        //        + currentAbonne.getNom() + " " + currentAbonne.getPrenom());
    }

    // ====================== SELECTION DANS TABLE ABONNEMENT ======================

    private void selectAbonnementFromTable() {
        int row = tableabonnement.getSelectedRow();
        if (row == -1) return;

        int idAbo = (int) tableabonnement.getValueAt(row, 0);
        Abonnement abo = abonnementService.findById(idAbo);

        if (abo != null) {
            currentAbonne = abo.getAbonne();
            typetxt.setSelectedItem(abo.getType());
            dureetxt.setText(String.valueOf(abo.getDuree()));
            prixtxt.setText(String.valueOf(abo.getPrix()));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        type = new javax.swing.JLabel();
        duree = new javax.swing.JLabel();
        prix = new javax.swing.JLabel();
        dureetxt = new javax.swing.JTextField();
        prixtxt = new javax.swing.JTextField();
        createbn = new javax.swing.JButton();
        updatebn = new javax.swing.JButton();
        deletebn = new javax.swing.JButton();
        typetxt = new javax.swing.JComboBox();
        nom = new javax.swing.JLabel();
        prenom = new javax.swing.JLabel();
        txtNomSearch = new javax.swing.JTextField();
        txtPrenomSearch = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableAbonne = new javax.swing.JTable();
        rechercherbn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableabonnement = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Abonnement");
        setToolTipText("");

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.black, java.awt.Color.black));

        type.setFont(new java.awt.Font("Century Schoolbook", 3, 14)); // NOI18N
        type.setText("Type:");

        duree.setFont(new java.awt.Font("Century Schoolbook", 3, 14)); // NOI18N
        duree.setText("Duree:");

        prix.setFont(new java.awt.Font("Century Schoolbook", 3, 14)); // NOI18N
        prix.setText("Prix:");

        dureetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dureetxtActionPerformed(evt);
            }
        });

        prixtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prixtxtActionPerformed(evt);
            }
        });

        createbn.setText("Ajouter");
        createbn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createbnActionPerformed(evt);
            }
        });

        updatebn.setText("Modifier");
        updatebn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebnActionPerformed(evt);
            }
        });

        deletebn.setText("Supprimer");
        deletebn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebnActionPerformed(evt);
            }
        });

        typetxt.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mensuel", "Annuel ", "Trimestriel" }));
        typetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typetxtActionPerformed(evt);
            }
        });

        nom.setFont(new java.awt.Font("Century Schoolbook", 3, 14)); // NOI18N
        nom.setText("Nom:");

        prenom.setFont(new java.awt.Font("Century Schoolbook", 3, 14)); // NOI18N
        prenom.setText("Prenom:");

        txtNomSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomSearchActionPerformed(evt);
            }
        });

        txtPrenomSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrenomSearchActionPerformed(evt);
            }
        });

        tableAbonne.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tableAbonne.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Nom", "Prenom", "Age", "Sexe"
            }
        ));
        jScrollPane1.setViewportView(tableAbonne);

        rechercherbn.setText("Recherche");
        rechercherbn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rechercherbnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Algerian", 3, 36)); // NOI18N
        jLabel1.setText("Formulaire Abonnement");

        jLabel2.setFont(new java.awt.Font("Algerian", 3, 36)); // NOI18N
        jLabel2.setText("Recherche d’abonné");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(prix)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(prixtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(duree)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(dureetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(type)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(typetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(141, 141, 141))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(52, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(createbn)
                .addGap(81, 81, 81)
                .addComponent(updatebn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(deletebn)
                .addGap(84, 84, 84))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(prenom)
                    .addComponent(nom))
                .addGap(88, 88, 88)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtNomSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrenomSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rechercherbn)
                .addGap(79, 79, 79))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nom)
                            .addComponent(txtNomSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(rechercherbn)
                        .addGap(7, 7, 7)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prenom)
                    .addComponent(txtPrenomSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(type)
                    .addComponent(typetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(duree)
                    .addComponent(dureetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prix)
                    .addComponent(prixtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createbn)
                    .addComponent(updatebn)
                    .addComponent(deletebn))
                .addGap(52, 52, 52))
        );

        jPanel2.setBackground(new java.awt.Color(255, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.black, java.awt.Color.black));

        tableabonnement.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "idabonne", "Type", "Duree", "Prix"
            }
        ));
        jScrollPane2.setViewportView(tableabonnement);

        jLabel3.setFont(new java.awt.Font("Algerian", 3, 36)); // NOI18N
        jLabel3.setText("TABLE ABONNEMENT");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(108, 108, 108))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(133, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dureetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dureetxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dureetxtActionPerformed

    private void createbnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createbnActionPerformed
        // TODO add your handling code here:
            if (currentAbonne == null) {
            JOptionPane.showMessageDialog(this,
                "Veuillez sélectionner un abonné !");
            return;
        }

        try {
            String type = typetxt.getSelectedItem().toString();
            int duree = Integer.parseInt(dureetxt.getText());
            double prix = Double.parseDouble(prixtxt.getText());

            Abonnement abo = new Abonnement(currentAbonne, type, duree, prix);

            if (abonnementService.create(abo)) {
                JOptionPane.showMessageDialog(this, "Abonnement ajouté !");
                loadAbonnements();
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,
                "Erreur : " + ex.getMessage());
        }
    }//GEN-LAST:event_createbnActionPerformed

    private void typetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typetxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_typetxtActionPerformed

    private void txtNomSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomSearchActionPerformed

    private void txtPrenomSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrenomSearchActionPerformed
        // TODO add your handling code here:
           String nom = txtNomSearch.getText().trim().toLowerCase();
        String prenom = txtPrenomSearch.getText().trim().toLowerCase();

        modelAbonne.setRowCount(0);

        for (Abonne a : allAbonnes) {
            if (a.getNom().toLowerCase().contains(nom)
                    && a.getPrenom().toLowerCase().contains(prenom)) {

                modelAbonne.addRow(new Object[]{
                    a.getId(), a.getNom(), a.getPrenom(), a.getAge(), a.getSexe()
                });
            }
        }
    }//GEN-LAST:event_txtPrenomSearchActionPerformed

    private void rechercherbnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rechercherbnActionPerformed
        // TODO add your handling code here:
         // Texte tapé dans les champs
    String nomStr = txtNomSearch.getText().trim().toLowerCase();
    String prenomStr = txtPrenomSearch.getText().trim().toLowerCase();

    // On vide le tableau
    modelAbonne.setRowCount(0);

    // On parcourt tous les abonnés chargés au départ
    for (Abonne a : allAbonnes) {
        boolean okNom = nomStr.isEmpty() 
                || a.getNom().toLowerCase().contains(nomStr);
        boolean okPrenom = prenomStr.isEmpty() 
                || a.getPrenom().toLowerCase().contains(prenomStr);

        if (okNom && okPrenom) {
            modelAbonne.addRow(new Object[]{
                a.getId(),
                a.getNom(),
                a.getPrenom(),
                a.getAge(),
                a.getSexe()
            });
        }
    }
    }//GEN-LAST:event_rechercherbnActionPerformed

    private void prixtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prixtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prixtxtActionPerformed

    private void updatebnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebnActionPerformed
        // TODO add your handling code here:
         int row = tableabonnement.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this,
                "Sélectionnez un abonnement !");
            return;
        }

        int idAbo = (int) tableabonnement.getValueAt(row, 0);
        Abonnement abo = abonnementService.findById(idAbo);

        try {
            abo.setType(typetxt.getSelectedItem().toString());
            abo.setDuree(Integer.parseInt(dureetxt.getText()));
            abo.setPrix(Double.parseDouble(prixtxt.getText()));

            if (abonnementService.update(abo)) {
                JOptionPane.showMessageDialog(this, "Modifié !");
                loadAbonnements();
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,
                "Erreur : " + ex.getMessage());
        }
    }//GEN-LAST:event_updatebnActionPerformed

    private void deletebnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebnActionPerformed
        // TODO add your handling code here:
        int row = tableabonnement.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this,
                "Sélectionnez un abonnement !");
            return;
        }

        int idAbo = (int) tableabonnement.getValueAt(row, 0);
        Abonnement abo = abonnementService.findById(idAbo);

        if (abonnementService.delete(abo)) {
            JOptionPane.showMessageDialog(this, "Supprimé !");
            loadAbonnements();
        }
    }//GEN-LAST:event_deletebnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createbn;
    private javax.swing.JButton deletebn;
    private javax.swing.JLabel duree;
    private javax.swing.JTextField dureetxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel nom;
    private javax.swing.JLabel prenom;
    private javax.swing.JLabel prix;
    private javax.swing.JTextField prixtxt;
    private javax.swing.JButton rechercherbn;
    private javax.swing.JTable tableAbonne;
    private javax.swing.JTable tableabonnement;
    private javax.swing.JTextField txtNomSearch;
    private javax.swing.JTextField txtPrenomSearch;
    private javax.swing.JLabel type;
    private javax.swing.JComboBox typetxt;
    private javax.swing.JButton updatebn;
    // End of variables declaration//GEN-END:variables
}
