/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;
import entities.Abonne;
import entities.Abonnement;
import services.AbonneService;
import services.AbonnementService;

import java.util.List;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author pc
 */
public class FiltrageFrame extends javax.swing.JInternalFrame {
      // =============== ATTRIBUTS METIER ===============
    private AbonneService abonneService;
    private AbonnementService abonnementService;

    private List<Abonne> allAbonnes;
    private List<Abonnement> allAbonnements;

    private DefaultTableModel modelAge;
    private DefaultTableModel modelType;

    /**
     * Creates new form FiltrageAgeFrame
     */
    public FiltrageFrame() {
        initComponents();

        // Initialisation services
        abonneService = new AbonneService();
        abonnementService = new AbonnementService();

        // Récupérer les modèles de tableaux
        modelAge = (DefaultTableModel) jTable1.getModel();
        modelType = (DefaultTableModel) jTable3.getModel();

        // Charger les données complètes au démarrage
        loadAbonnes();
        loadAbonnements();
    }

    // =============== CHARGEMENT DES DONNEES ===============

    private void loadAbonnes() {
        allAbonnes = abonneService.findAll();
        modelAge.setRowCount(0);

        for (Abonne a : allAbonnes) {
            modelAge.addRow(new Object[]{
                a.getId(),
                a.getNom(),
                a.getPrenom(),
                a.getAge(),
                a.getSexe()
            });
        }
    }

    private void loadAbonnements() {
        allAbonnements = abonnementService.findAll();
        modelType.setRowCount(0);

        for (Abonnement abo : allAbonnements) {
            Abonne a = abo.getAbonne();
            String nomComplet = (a != null) ? a.getNom() + " " + a.getPrenom() : "";

            modelType.addRow(new Object[]{
                abo.getId(),
                nomComplet,          // colonne "Idabonne" mais on affiche Nom + Prénom
                abo.getType(),
                abo.getDuree(),
                abo.getPrix()
            });
        }
    }

    // =====================================================
    // ================== CODE NETBEANS =====================
    // =====================================================

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        filtrageage = new javax.swing.JLabel();
        filtrageagecb = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        filtrageagebn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        filtragetypecb = new javax.swing.JComboBox();
        filtragetype = new javax.swing.JLabel();
        filtragetypebn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Filtrage");

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        filtrageage.setFont(new java.awt.Font("Century Schoolbook", 3, 14)); // NOI18N
        filtrageage.setText("Filtrage par age :");

        filtrageagecb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Toutes", "Moins de 18 ans", "18 - 25 ans", "26 - 35 ans", "36 - 45 ans", "Plus de 45 ans" }));
        filtrageagecb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filtrageagecbActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Nom", "Prenom", "Age", "Sexe"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        filtrageagebn.setText("FiltrageAge");
        filtrageagebn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filtrageagebnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Algerian", 3, 36)); // NOI18N
        jLabel1.setText("Filtrage Age");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-filtrage-des-données-66.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(48, 48, 48)
                .addComponent(filtrageage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(filtrageagecb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(filtrageagebn)
                .addGap(148, 148, 148))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel1)
                        .addGap(32, 32, 32)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(filtrageagecb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(filtrageage))
                        .addGap(55, 55, 55)))
                .addComponent(filtrageagebn)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Idabonne", "Type", "Duree", "Prix"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        filtragetypecb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Tous", "Mensuel", "Trimestriel", "Annuel" }));
        filtragetypecb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filtragetypecbActionPerformed(evt);
            }
        });

        filtragetype.setFont(new java.awt.Font("Century Schoolbook", 3, 14)); // NOI18N
        filtragetype.setText("Filtrage par type:");

        filtragetypebn.setText("FiltrageType");
        filtragetypebn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filtragetypebnActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Algerian", 3, 36)); // NOI18N
        jLabel2.setText("Filtrage Type");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-recherche-50 (1).png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(filtragetype)
                .addGap(72, 72, 72)
                .addComponent(filtragetypecb, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addGap(23, 23, 23))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addComponent(filtragetypebn))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel2)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(filtragetype)
                            .addComponent(filtragetypecb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(59, 59, 59))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)))
                .addComponent(filtragetypebn)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 101, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void filtrageagecbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filtrageagecbActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_filtrageagecbActionPerformed

    private void filtrageagebnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filtrageagebnActionPerformed
        // TODO add your handling code here:
         String choix = filtrageagecb.getSelectedItem().toString();
        modelAge.setRowCount(0);

        for (Abonne a : allAbonnes) {
            int age = a.getAge();
            boolean ok = false;

            switch (choix) {
                case "Toutes":
                    ok = true;
                    break;
                case "Moins de 18 ans":
                    ok = age < 18;
                    break;
                case "18 - 25 ans":
                    ok = (age >= 18 && age <= 25);
                    break;
                case "26 - 35 ans":
                    ok = (age >= 26 && age <= 35);
                    break;
                case "36 - 45 ans":
                    ok = (age >= 36 && age <= 45);
                    break;
                case "Plus de 45 ans":
                    ok = age > 45;
                    break;
            }

            if (ok) {
                modelAge.addRow(new Object[]{
                    a.getId(),
                    a.getNom(),
                    a.getPrenom(),
                    a.getAge(),
                    a.getSexe()
                });
            }
        }
    }//GEN-LAST:event_filtrageagebnActionPerformed

    private void filtragetypecbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filtragetypecbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_filtragetypecbActionPerformed

    private void filtragetypebnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filtragetypebnActionPerformed
        // TODO add your handling code here:
         String choixType = filtragetypecb.getSelectedItem().toString();
        modelType.setRowCount(0);

        for (Abonnement abo : allAbonnements) {
            boolean ok = choixType.equals("Tous")
                         || abo.getType().equalsIgnoreCase(choixType.trim());

            if (ok) {
                Abonne a = abo.getAbonne();
                String nomComplet = (a != null) ? a.getNom() + " " + a.getPrenom() : "";

                modelType.addRow(new Object[]{
                    abo.getId(),
                    nomComplet,
                    abo.getType(),
                    abo.getDuree(),
                    abo.getPrix()
                });
            }
        }
    }//GEN-LAST:event_filtragetypebnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel filtrageage;
    private javax.swing.JButton filtrageagebn;
    private javax.swing.JComboBox filtrageagecb;
    private javax.swing.JLabel filtragetype;
    private javax.swing.JButton filtragetypebn;
    private javax.swing.JComboBox filtragetypecb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable3;
    // End of variables declaration//GEN-END:variables
}
