/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import entities.Abonne;
import entities.Abonnement;
import entities.Paiement;
import services.AbonneService;
import services.AbonnementService;
import services.PaiementService;

import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author pc
 */
public class PaiementFrame extends javax.swing.JInternalFrame {

    
    // ====== ATTRIBUTS MÉTIER ======
    private AbonneService abonneService;
    private AbonnementService abonnementService;
    private PaiementService paiementService;

    private DefaultTableModel modelAbonne;
    private DefaultTableModel modelPaiement;

    private List<Abonne> allAbonnes;

    private Abonne currentAbonne;
    private Paiement currentPaiement;

    /**
     * Creates new form PaiementFrame
     */
    public PaiementFrame() {
        initComponents();

        abonneService = new AbonneService();
        abonnementService = new AbonnementService();
        paiementService = new PaiementService();

        modelAbonne = (DefaultTableModel) jTable1.getModel();
        modelPaiement = (DefaultTableModel) jTable2.getModel();

        loadAllAbonnes();
        loadPaiements();

        // sélection dans la table des abonnés
        jTable1.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (!e.getValueIsAdjusting()) {
                    selectAbonneFromTable();
                }
            }
        });

        // sélection dans la table des paiements
        jTable2.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (!e.getValueIsAdjusting()) {
                    selectPaiementFromTable();
                }
            }
        });
    }

    // ================= CHARGEMENT DES DONNÉES =================

    private void loadAllAbonnes() {
        allAbonnes = abonneService.findAll();
        modelAbonne.setRowCount(0);

        for (Abonne a : allAbonnes) {
            modelAbonne.addRow(new Object[]{
                a.getId(), a.getNom(), a.getPrenom(), a.getAge(), a.getSexe()
            });
        }
    }

    private void loadPaiements() {
        modelPaiement.setRowCount(0);

        for (Paiement p : paiementService.findAll()) {
            Abonne a = p.getAbonne();
            String nomComplet = (a != null) ? a.getNom() + " " + a.getPrenom() : "";
            LocalDate d = p.getDatePaiement();

            modelPaiement.addRow(new Object[]{
                p.getId(),
                nomComplet,          // colonne "idabonne" mais on affiche nom + prénom
                d,
                p.getMontant()
            });
        }
    }

    // ================= SELECTION DANS LES TABLES =================

    private void selectAbonneFromTable() {
        int row = jTable1.getSelectedRow();
        if (row == -1) return;

        int idAbonne = (int) jTable1.getValueAt(row, 0);
        currentAbonne = abonneService.findById(idAbonne);
    }

    private void selectPaiementFromTable() {
        int row = jTable2.getSelectedRow();
        if (row == -1) return;

        int id = (int) jTable2.getValueAt(row, 0);
        Paiement p = paiementService.findById(id);
        if (p == null) return;

        currentPaiement = p;
        currentAbonne = p.getAbonne();

        // remplir les champs
        montanttxt.setText(String.valueOf(p.getMontant()));
        LocalDate d = p.getDatePaiement();
        if (d != null) {
            DateChooser2.setDate(java.sql.Date.valueOf(d));
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Recherchebn = new javax.swing.JButton();
        nomtxt = new javax.swing.JTextField();
        prenomtxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        datepaiement = new javax.swing.JLabel();
        montant = new javax.swing.JLabel();
        DateChooser2 = new com.toedter.calendar.JDateChooser();
        montanttxt = new javax.swing.JTextField();
        createbn = new javax.swing.JButton();
        updatebn = new javax.swing.JButton();
        deletebn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        jLabel3.setFont(new java.awt.Font("Century Schoolbook", 3, 14)); // NOI18N
        jLabel3.setText("Nom :");

        jLabel4.setFont(new java.awt.Font("Century Schoolbook", 3, 14)); // NOI18N
        jLabel4.setText("Prenom :");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Nom", "Prenom", "Age", "Sexe"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        Recherchebn.setText("Recherche");
        Recherchebn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RecherchebnActionPerformed(evt);
            }
        });

        nomtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomtxtActionPerformed(evt);
            }
        });

        prenomtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prenomtxtActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Algerian", 3, 36)); // NOI18N
        jLabel1.setText("Recherche d’abonné");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(93, 93, 93))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(83, 83, 83))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nomtxt, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                            .addComponent(prenomtxt))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Recherchebn)
                        .addGap(65, 65, 65))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(nomtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(prenomtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(Recherchebn)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        jPanel2.setBackground(new java.awt.Color(255, 204, 204));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "idabonne", "DatePaiement", "Montant"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jLabel5.setFont(new java.awt.Font("Algerian", 3, 36)); // NOI18N
        jLabel5.setText("Table Paiement ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 204, 204));

        datepaiement.setFont(new java.awt.Font("Century Schoolbook", 3, 14)); // NOI18N
        datepaiement.setText("Date de paiement:");

        montant.setFont(new java.awt.Font("Century Schoolbook", 3, 14)); // NOI18N
        montant.setText("Montant:");

        montanttxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                montanttxtActionPerformed(evt);
            }
        });

        createbn.setText("Ajouter");
        createbn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createbnActionPerformed(evt);
            }
        });

        updatebn.setText("Modifier");
        updatebn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebnActionPerformed(evt);
            }
        });

        deletebn.setText("Supprimer");
        deletebn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebnActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Algerian", 3, 36)); // NOI18N
        jLabel2.setText("Formulaire Paiement");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(createbn)
                .addGap(110, 110, 110)
                .addComponent(updatebn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(deletebn)
                .addGap(96, 96, 96))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(112, 112, 112))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(datepaiement)
                    .addComponent(montant))
                .addGap(66, 66, 66)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(DateChooser2, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                    .addComponent(montanttxt))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(36, 36, 36)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(datepaiement)
                    .addComponent(DateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(montant)
                    .addComponent(montanttxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createbn)
                    .addComponent(updatebn)
                    .addComponent(deletebn))
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(379, 379, 379))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nomtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomtxtActionPerformed

    private void prenomtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prenomtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prenomtxtActionPerformed

    private void RecherchebnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RecherchebnActionPerformed
        // TODO add your handling code here:
        String nomStr = nomtxt.getText().trim().toLowerCase();
        String prenomStr = prenomtxt.getText().trim().toLowerCase();

        modelAbonne.setRowCount(0);

        for (Abonne a : allAbonnes) {
            boolean okNom = nomStr.isEmpty() || a.getNom().toLowerCase().contains(nomStr);
            boolean okPrenom = prenomStr.isEmpty() || a.getPrenom().toLowerCase().contains(prenomStr);

            if (okNom && okPrenom) {
                modelAbonne.addRow(new Object[]{
                    a.getId(), a.getNom(), a.getPrenom(), a.getAge(), a.getSexe()
                });
            }
        }
    }//GEN-LAST:event_RecherchebnActionPerformed

    private void montanttxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_montanttxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_montanttxtActionPerformed

    private void createbnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createbnActionPerformed
        // TODO add your handling code here:
        if (currentAbonne == null) {
            JOptionPane.showMessageDialog(this, "Sélectionnez un abonné !");
            return;
        }

        Date utilDate = DateChooser2.getDate();
        if (utilDate == null) {
            JOptionPane.showMessageDialog(this, "Choisissez une date de paiement !");
            return;
        }

        try {
            LocalDate dateP = utilDate.toInstant()
                                      .atZone(ZoneId.systemDefault())
                                      .toLocalDate();
            double montantVal = Double.parseDouble(montanttxt.getText().trim());

            // récupérer l’abonnement de cet abonné
            List<Abonnement> abos = abonnementService.findByAbonne(currentAbonne.getId());
            if (abos.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Cet abonné n’a aucun abonnement !");
                return;
            }
            Abonnement abo = abos.get(0); // on prend le premier (ou le seul)

            Paiement p = new Paiement();
            p.setAbonne(currentAbonne);
            p.setAbonnement(abo);
            p.setDatePaiement(dateP);
            p.setMontant(montantVal);

            if (paiementService.create(p)) {
                JOptionPane.showMessageDialog(this, "Paiement ajouté !");
                loadPaiements();
            }

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Montant invalide !");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Erreur : " + ex.getMessage());
        }
    }//GEN-LAST:event_createbnActionPerformed

    private void updatebnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebnActionPerformed
        // TODO add your handling code here:
        int row = jTable2.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Sélectionnez un paiement !");
            return;
        }

        int id = (int) jTable2.getValueAt(row, 0);
        Paiement p = paiementService.findById(id);
        if (p == null) return;

        Date utilDate = DateChooser2.getDate();
        if (utilDate == null) {
            JOptionPane.showMessageDialog(this, "Choisissez une date de paiement !");
            return;
        }

        try {
            LocalDate dateP = utilDate.toInstant()
                                      .atZone(ZoneId.systemDefault())
                                      .toLocalDate();
            double montantVal = Double.parseDouble(montanttxt.getText().trim());

            // garder le même abonnement
            p.setDatePaiement(dateP);
            p.setMontant(montantVal);

            if (paiementService.update(p)) {
                JOptionPane.showMessageDialog(this, "Paiement modifié !");
                loadPaiements();
            }

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Montant invalide !");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Erreur : " + ex.getMessage());
        }
    }//GEN-LAST:event_updatebnActionPerformed

    private void deletebnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebnActionPerformed
        // TODO add your handling code here:
        int row = jTable2.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Sélectionnez un paiement !");
            return;
        }

        int id = (int) jTable2.getValueAt(row, 0);
        Paiement p = paiementService.findById(id);
        if (p == null) return;

        if (paiementService.delete(p)) {
            JOptionPane.showMessageDialog(this, "Paiement supprimé !");
            loadPaiements();
        }
    }//GEN-LAST:event_deletebnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser DateChooser2;
    private javax.swing.JButton Recherchebn;
    private javax.swing.JButton createbn;
    private javax.swing.JLabel datepaiement;
    private javax.swing.JButton deletebn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel montant;
    private javax.swing.JTextField montanttxt;
    private javax.swing.JTextField nomtxt;
    private javax.swing.JTextField prenomtxt;
    private javax.swing.JButton updatebn;
    // End of variables declaration//GEN-END:variables
}
