/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;
import java.util.Properties;
import javax.mail.*;
import javax.mail.internet.*;
import javax.swing.JOptionPane;
import services.*;
/**
 *
 * @author pc
 */
public class UserFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form LoginFrame
     */
    public UserFrame() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        backgroundPanel = new ui.GradientPanel();
        cardPanel = new ui.RoundedPanel();
        imagePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        roundedPanel1 = new ui.RoundedPanel();
        jLabel2 = new javax.swing.JLabel();
        usernametxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        loginbn = new javax.swing.JButton();
        passwordbn = new javax.swing.JButton();
        passwordtxt = new javax.swing.JTextField();
        login = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        jLabel4.setText("jLabel4");

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        getContentPane().setLayout(null);

        backgroundPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cardPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imagePanel.setOpaque(false);
        imagePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/HO4.jpg"))); // NOI18N
        imagePanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-80, -90, -1, 580));

        cardPanel.add(imagePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 360, 410));

        backgroundPanel.add(cardPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 400, 450));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("User Name :");

        usernametxt.setText(" ");
        usernametxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernametxtActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Password :");

        loginbn.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        loginbn.setText("Login");
        loginbn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        loginbn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginbnActionPerformed(evt);
            }
        });

        passwordbn.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        passwordbn.setText("Forgot password");
        passwordbn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        passwordbn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordbnActionPerformed(evt);
            }
        });

        passwordtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordtxtActionPerformed(evt);
            }
        });

        login.setFont(new java.awt.Font("Century Schoolbook", 3, 36)); // NOI18N
        login.setText("LOGIN");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-user-30.png"))); // NOI18N

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-password-30.png"))); // NOI18N

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-fitness-50.png"))); // NOI18N

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-login-30.png"))); // NOI18N

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-forgot-password-32.png"))); // NOI18N

        javax.swing.GroupLayout roundedPanel1Layout = new javax.swing.GroupLayout(roundedPanel1);
        roundedPanel1.setLayout(roundedPanel1Layout);
        roundedPanel1Layout.setHorizontalGroup(
            roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundedPanel1Layout.createSequentialGroup()
                .addGap(0, 52, Short.MAX_VALUE)
                .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(roundedPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(289, 289, 289))
                    .addGroup(roundedPanel1Layout.createSequentialGroup()
                        .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(roundedPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(28, 28, 28)
                                .addComponent(loginbn)))
                        .addGap(53, 53, 53)
                        .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundedPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(33, 33, 33)
                                .addComponent(passwordbn)
                                .addGap(24, 24, 24))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundedPanel1Layout.createSequentialGroup()
                                .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(usernametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(passwordtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(41, 41, 41))))))
            .addGroup(roundedPanel1Layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        roundedPanel1Layout.setVerticalGroup(
            roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanel1Layout.createSequentialGroup()
                .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(roundedPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel8))
                    .addGroup(roundedPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(roundedPanel1Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jLabel6)))
                        .addGap(23, 23, 23)
                        .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(roundedPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7))
                            .addGroup(roundedPanel1Layout.createSequentialGroup()
                                .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                                    .addComponent(usernametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(41, 41, 41)
                                .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(passwordtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                        .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addComponent(passwordbn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(loginbn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        backgroundPanel.add(roundedPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 60, 480, 350));

        getContentPane().add(backgroundPanel);
        backgroundPanel.setBounds(0, -10, 950, 520);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usernametxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernametxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernametxtActionPerformed

    private void loginbnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginbnActionPerformed
                                                  
    // 1) Récupérer les valeurs saisies
    String loginStr = usernametxt.getText().trim();
    String password = passwordtxt.getText().trim();

    // 2) Vérifier que les champs ne sont pas vides
    if (loginStr.isEmpty() || password.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Veuillez saisir le login et le mot de passe.",
                "Champs manquants",
                javax.swing.JOptionPane.WARNING_MESSAGE
        );
        return;
    }

    // 3) Appeler le service d'authentification
    services.UserService us = new services.UserService();

    if (us.authenticate(loginStr, password)) {
        // --- Connexion OK ---
        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Connexion réussie, bienvenue " + loginStr + " !"
        );

        // 4) Ouvrir la fenêtre principale (Main)
        Main mainFrame = new Main();
        mainFrame.setLocationRelativeTo(null);   // centre la fenêtre
        mainFrame.setVisible(true);

        // 5) Fermer la fenêtre de login (JInternalFrame + JFrame parent)
        java.awt.Window parentWindow =
                javax.swing.SwingUtilities.getWindowAncestor(this);
        if (parentWindow != null) {
            parentWindow.dispose();   // ferme la JFrame qui contient UserFrame
        } else {
            this.dispose();           // au cas où
        }

    } else {
        // --- Connexion KO ---
        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Login ou mot de passe incorrect.",
                "Erreur",
                javax.swing.JOptionPane.ERROR_MESSAGE
        );
    }
    }//GEN-LAST:event_loginbnActionPerformed

    
    private void passwordbnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordbnActionPerformed
       String login = usernametxt.getText().trim();  // ici tu saisis le login : "hiba"

    if (login.isEmpty()) {
        JOptionPane.showMessageDialog(this,
                "Saisis ton nom d'utilisateur (login) avant de cliquer.",
                "Info",
                JOptionPane.INFORMATION_MESSAGE);
        return;
    }

    // Service
    services.UserService us = new services.UserService();

    // 1) Chercher l'utilisateur
    entities.User user = us.findUserByLogin(login);
    if (user == null) {
        JOptionPane.showMessageDialog(this,
                "Utilisateur introuvable.",
                "Erreur",
                JOptionPane.ERROR_MESSAGE);
        return;
    }

    // 2) Générer un nouveau mot de passe
    String newPassword = us.generateTemporaryPassword();

    // 3) Mettre à jour le mot de passe dans la base
    boolean ok = us.updatePassword(login, newPassword);

    if (!ok) {
        JOptionPane.showMessageDialog(this,
                "Erreur lors de la mise à jour du mot de passe.",
                "Erreur",
                JOptionPane.ERROR_MESSAGE);
        return;
    }

    // 4) Envoyer l'email avec le NOUVEAU mot de passe
    try {
        sendForgotPasswordMail(user.getEmail(), newPassword);
        JOptionPane.showMessageDialog(this,
                "Un nouveau mot de passe a été envoyé à : " + user.getEmail(),
                "Succès",
                JOptionPane.INFORMATION_MESSAGE);
    } catch (Exception ex) {
        ex.printStackTrace();
        JOptionPane.showMessageDialog(this,
                "Erreur lors de l'envoi de l'e-mail.",
                "Erreur",
                JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_passwordbnActionPerformed

    private void passwordtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordtxtActionPerformed
         loginbnActionPerformed(evt);
    }//GEN-LAST:event_passwordtxtActionPerformed

   
   // --- Envoi e-mail simple ---
private void sendForgotPasswordMail(String toEmail, String newPassword) throws MessagingException {
          
    final String fromEmail   = "hiba.ouirouane.05@gmail.com";      // ton Gmail
    final String appPassword = "ygqmldbvooguwtze";                 // ton app password

    Properties props = new Properties();
    props.put("mail.smtp.auth", "true");
    props.put("mail.smtp.starttls.enable", "true");
    props.put("mail.smtp.host", "smtp.gmail.com");
    props.put("mail.smtp.port", "587");

    Session session = Session.getInstance(props, new Authenticator() {
        @Override
        protected PasswordAuthentication getPasswordAuthentication() {
            return new PasswordAuthentication(fromEmail, appPassword);
        }
    });

    Message message = new MimeMessage(session);
    message.setFrom(new InternetAddress(fromEmail));
    message.setRecipients(Message.RecipientType.TO, InternetAddress.parse(toEmail));
    message.setSubject("Mot de passe oublié - Salle de Sport");
    message.setText(
        "Bonjour,\n\n"
      + "Une demande de réinitialisation de mot de passe a été effectuée.\n"
      + "Votre nouveau mot de passe temporaire est : " + newPassword + "\n\n"
      + "Veuillez vous connecter avec ce mot de passe puis le modifier.\n\n"
      + "Salle de Sport."
    );

    Transport.send(message);
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ui.GradientPanel backgroundPanel;
    private ui.RoundedPanel cardPanel;
    private javax.swing.JPanel imagePanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel login;
    private javax.swing.JButton loginbn;
    private javax.swing.JButton passwordbn;
    private javax.swing.JTextField passwordtxt;
    private ui.RoundedPanel roundedPanel1;
    private javax.swing.JTextField usernametxt;
    // End of variables declaration//GEN-END:variables
}
